require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods', :deterministic_uuids => false

platform :ios, '10.0'

target 'ScalePractice' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"],
    :hermes_enabled => false
  )

  target 'ScalePracticeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  
  # use_flipper!
  post_install do |installer|
  # flipper_post_install(installer)

    installer.pods_project.targets.each do |target|

      # The following is needed to ensure the "archive" step works in XCode.
      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      # Without this, you'd see errors when you archive like:
      # "Multiple commands produce ... libReact.a"
      # "Multiple commands produce ... libyoga.a"

      targets_to_ignore = %w(React yoga)
      
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
  end
end

target 'ScalePractice-tvOS' do
  # Pods for ScalePractice-tvOS

  target 'ScalePractice-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
